services:
  - type: web
    name: searchbox-backend
    env: ruby
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bin/render-deploy
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: searchbox-instance
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: DISABLE_DATABASE_ENVIRONMENT_CHECK
        value: 1

databases:
  - name: searchbox-instance
    databaseName: searchbox_db
    user: searchbox_user

  - type: redis
    name: searchbox-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free 